version: "3.9"

services:
  database:
    image: "postgres:latest"
    container_name: pdb
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

    volumes:
      - ./pdb-data/:/var/lib/postgresql/data/
