spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 3
